language: python
cache:
  directories:
  - $HOME/.cache/pip
  - .tox

jobs:
    include:
        # Run as root
        - os: linux
          python: 2.7
          env:
            - TOXENV=py27-linux_non_root,py27-linux_root,codecov

        - os: linux
          python: pypy
          env:
            - TOXENV=pypy-linux_non_root,pypy-linux_root,codecov

        - os: linux
          python: pypy3
          env:
            - TOXENV=pypy3-linux_non_root,pypy3-linux_root,codecov

        - os: linux
          python: 3.5
          env:
            - TOXENV=py35-linux_root,codecov

        - os: linux
          python: 3.6
          env:
            - TOXENV=py36-linux_root,codecov

        - os: linux
          python: 3.7
          env:
            - TOXENV=py37-linux_root,codecov

        - os: linux
          python: 3.8
          env:
            - TOXENV=py38-linux_non_root,py38-linux_root,codecov

        - os: osx
          language: generic
          env:
            - TOXENV=py27-bsd_non_root,py27-bsd_root,codecov
        - os: osx
          language: generic
          env:
            - TOXENV=py36-bsd_non_root,py36-bsd_root,codecov

        - os: linux
          python: 3.8
          env:
            - TOXENV=py38-isotp_kernel_module,codecov

        - os: linux
          python: 3.8
          env:
            - SCAPY_USE_PCAPDNET=yes TOXENV=py38-linux_root,codecov

        # Other root tests
        # Test scapy against all warnings
        - os: linux
          python: 3.8
          env:
            - SCAPY_PY_OPTS="-Werror -X tracemalloc=25" TOXENV=py38-linux_root
    allow_failures:
      - env: SCAPY_PY_OPTS="-Werror -X tracemalloc=25" TOXENV=py38-linux_root

install:
  - bash .config/ci/install.sh
  - python -c "from scapy.all import conf; print(repr(conf))"

script: bash .config/ci/test.sh
